### ISSUE TITLE
It should possible to pass `children` as an argument to a Brick

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#1027]
See https://github.com/mila-udem/blocks/pull/1021#issuecomment-195388088

The PR should also include refactoring of all existing bricks. They should use pass children to the superclass constructor instead of using `self.children =`.

**Comment by memimo** [comment]
It raises some issue though, some of the bricks need to call super.__init__ to be able to construct their children. For example in SequenceContentAttention, it needs to call super().__init__ to have self.state_names in order to construct one state_transformers which is a child.
I'm not familiar with Parallel class, but if this is the only case, I can call init with the prototype then change state_transformers to Parrallel.

**Comment by rizar** [comment]
I see. I would rather say that it's a fault of `SequenceContentAttention` that it has such a hacky constructor. You can fetch `state_names` from kwargs, that is `kwargs['state_names']`, and use them to create children.
