### ISSUE TITLE
Model rationale

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#613]
I'm still a bit hazy on why one needs the `Model` abstraction at all. It would be good to try and document this somewhere in the narrative documentation, and probably say a little something about it in the docstring.

**Comment by bartvm** [comment]
Haha, oh dear, let the discussion begin... The discussion has been a bit all over the place, but this is a good place to start I guess: https://github.com/bartvm/blocks/issues/347 Personally, I agree that there is little reason for the `Model` abstraction. There are a few good use cases that @rizar has brought up, but I think they can be served by a much lighter object (basically, a kind of mutable computation graph).

**Comment by rizar** [comment]
I would be quite happy to simply get rid of it and rename the main loop's argument into `computation_graph`. I have two main concerns: first is that there is no single right way of retrieving parameters from a computation graph, second that the cost graph might not always contain references to all bricks involved (a very hypothetical case). So the model idea was that it should be something that answers these two requests: what are the parameters and what are the bricks. Also I thought users could inherit from it and add some functionality they find useful.

But it ends up being so confusing that we should probably go the way @bartvm proposes. And for extension by inheritance bricks seem to be better candidates, as long as the top brick can be simply retrieved from the graph.

**Comment by rizar** [comment]
Instead further polluting #347 I think I will post it here.

For the record, I think I know how to keep things both flexible and clean with `Model` class. Instead of it, let's add another member to the main loop, `main_loop.extension_config` of `ExtensionConfig`. As it follows from the name, such a class will contain configuration shared by all extensions, such as parameters and bricks. It will have a few properties with default implementations, e.g. `parameters`:

```
class ExtensionConfig(object):

  @property
  def parameters(self):
    # This is reasonable default
    if not self._parameters:
      return self.main_loop.computation_graph.shared_variables

  @parameters.setter
  def parameters(self, params)
    self._parameters = params
```

This way by passing `extension_config=ExtensionConfig(parameters=cg.parameters)` one can override the default for all extensions.

Put it differently, I propose to split the current abstract `Model` class into two concrete: `BrickComputationGraph` and `ExtensionConfig`.
