### ISSUE TITLE
Nesterov momentum

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [mila-udem/blocks#762]
Change the gradient descent to be able to create NAG-like steps and implement NAG.

**Comment by dmitriy-serdyuk** [comment]
@Thrandis , this is your CCW ticket.

**Comment by Thrandis** [comment]
@dmitriy-serdyuk, I just started my ccw ticket. Looking at lisa-lab/pylearn2#1030, I could implement NAG like in: http://arxiv.org/pdf/1212.0901v2.pdf, ie:

v_t = mu_t-1*v_t-1 - e_t-1*grad(f(theta_t-1)) = mu_t-1*v_t-1 + previous_step
theta_t = theta_t-1 + mu_t*mu_t-1*v_t - (1 + mu_t)*e_t-1*grad(f(theta_t-1)) 
            =  theta_t-1 + mu_t*mu_t-1*v_t + (1 + mu_t)*previous_step

In the code, it would roughly be something like:
```python
def compute_step(self, parameter, previous_step):
    velocity = shared_floatx(parameter.get_value() * 0.)
    velocity_update = self.momentum*velocity + previous_step
    step = self.momentum**2 * velocity + previous_step * (1 + self.momentum)
    updates = [(velocity, velocity_update)]
    return step, updates
```
It should work, since the step update is performed before the velocity update.
What do you think? We just have to keep in memory the previous value of mu (`mu_t-1`) and we don't need to change the `GradientDescent` class!

**Comment by dmitriy-serdyuk** [comment]
@Thrandis , sounds good. I wonder if it's slower than a naïve implementation.

I think we need to add it into blocks-extras repo.

**Comment by Thrandis** [comment]
@dmitriy-serdyuk, otherwise, we can add a flag to the basic momentum rule to choose between satandard and Nesterov momentum. I don't know what is the cleanest way to do it!

**Comment by dmitriy-serdyuk** [comment]
No, a flag isn't a neat solution.

**Comment by Thrandis** [comment]
All right, I'll add it into blocks-extras then!

**Comment by dwf** [comment]
Have a look at Nicolas Boulanger Lewandowski's thesis, he has some algebra
about Nesterov momentum in there that relates it to standard momentum,
might be useful.

**Comment by Thrandis** [comment]
All right! I'll take a look!
