### ISSUE TITLE
Better document selection of descendant parameters of bricks in Selector

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#771]
It would be nice to, for example, select all of the parameters in a nested, composite brick using the VariableFilter. A good example would be encoders and decoders, each of which might consist of many internal bricks. Another good example is the generator/discriminator in adversarial nets. This should probably be implemented separately from the `bricks` argument, perhaps with an `ancestor_bricks` argument?

**Comment by rizar** [comment]
`Selector` was intended to be used for such purposes. More specifically, it should have (somehow currently it doesn't) a `get_bricks` method that selects all ancestor bricks for a selection. Then you can pass all these bricks to `VariableFilter`. This way you can keep `VariableFilter` an easy tool.

In fact `Selector` was meant to do much more than it can do now, just that this component has received the least development time compared to others.

**Comment by dwf** [comment]
The `Selector` seems like an odd place for this, to be honest. For one thing, traversing upward in the brick hierarchy is non-trivial if not impossible, which is what a `Selector` would need to do. It seems as though `Selector` only knows about the bricks passed in the constructor and treats that as the top-level 'namespace' of the path given -- why does it make sense for the `Selector` to transcend this namespace? (`get_bricks` does not seem very informative for a name, either.)

Or are you suggesting that the `Selector` should be able to find all *descendant* bricks? That seems a bit more reasonable and doable, though I would still think that the cognitive overhead for the user is lower if we just allow an `ancestor_bricks` argument (possibly implemented with a new and improved `Selector`, I don't know).

**Comment by rizar** [comment]
> Or are you suggesting that the Selector should be able to find all descendant bricks?

Exactly, just like currently it can find all the parameters of all the descendants of a brick (wow, isn't it by chance just the usecase you need)?

> though I would still think that the cognitive overhead for the user is lower if we just allow an `ancestor_bricks`

It is a classic dilemma, have a single class with many methods that the users can use to solve all their problems or have a bunch  of classes that can by design do orthogonal things and can be combined to solve problems. Sort of Keras vs. Blocks (from Keras demos it seems like all you have to do is `model. this` and `model.that`). 

I am more in favour of the design in which `VariableFilter` knows very little about bricks. It is basically a set of very simply predicates for an annotated Theano variable. On the other hand, `Selector` would be the interface to bricks hierarchy, able to select a set of bricks and even attributes of a set of bricks.

**Comment by dwf** [comment]
I just read your response in detail. I hadn't realized that get_parameters() operated recursively! I think the word "ancestors" tripped me up. I'm sending a PR to improve the docs and add examples.
