### ISSUE TITLE
Cannot infer shape of Convolutional brick

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [mila-udem/blocks#825]
See discussion [here](https://groups.google.com/forum/#!topic/blocks-users/H8vjXOLbRFw).

**Comment by vzhong** [comment]
hey @dmitriy-serdyuk , I attempted a simple fix according to your suggestions. Another problem arises when `image_size` is defaulted to `(None, None)` in that allocation for `b` will fail due to `self.get_dim('output')` returning a shape of `(batch_size, None, None)`. This seems to make sense because I think variable input shapes probably requires tying the biases (right?). I've added an error message in the event we reach allocation and the input shapes are still not known. Let me know what you think :)

**Comment by dmitriy-serdyuk** [comment]
Thank you, this should work. You are right, one cannot use untied biases with variable input.

Can you make a pull request?

**Comment by vzhong** [comment]
Made one at #827
