### ISSUE TITLE
The BoundApplication.__getattr__ implementation is tricky, are you following some design pattern?

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/blocks#939]
Are you following some design pattern or anything else?

**Comment by wenhuchen** [comment]
I also think it's quite tricky, I spent quite some time understanding its calling procedure, but no idea why they make things so complex

**Comment by rizar** [comment]
Our design goal in this case was to allow application methods have attributes, or properties, like we usually call them in Blocks, such as `mlp.apply.inputs`, `mlp.apply.outputs`, etc. The tricky part is that in some cases they only become known at runtime. That's why we wanted a mechanism of requesting the value of the property directly from the brick object, see [this line](https://github.com/mila-udem/blocks/blob/master/blocks/bricks/base.py#L346). 

It did end up quite complicated, and `RecurrentStack`proposes a simpler paradigm when properties are set in the constructor, which could possibly be reused in other places.

**Comment by dwf** [comment]
I don't think there's anything actually left to do here, so I'll close it.
