### ISSUE TITLE
mask and cost in bidirectional recurrent networks

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/blocks#952]
<pre><code>
        if mask:
            next_states = (mask[:, None] * next_states +
                           (1 - mask[:, None]) * states)
</code></pre>
In blocks.bricks.recurrent , the next state is set to the same value as the previous state if its mask value is 0. Why not just set them to zeros?
Although it may not influence the final result, this would cause some inconsistency when applying mask to bidirectional recurrent networks.
Suppose that the last few time steps of a sample's mask is 0. When calculating the backward states, the inputs with mask 0 are fed in first. Then the states would copy the initial states, which are all zeros by default. Finally this state sequence is reversed an concatenated to the forward state sequence. The last time steps of the forward state sequence is equal to the last state whose input mask is 1. 
If the states with input mask 0 are set to 0, this inconsistency wouldn't exist. 

<pre><code>
return ((cost * y_mask).sum()) / y_mask.sum()
</code></pre>
Besides, when the cost is multiplied by y_mask, the last few cost values are set to zeros. Are these zeros still function of the parameters? Would they affect the gradient calculation?

**Comment by rizar** [comment]
Sorry for the late reply!

I agree that it might be confusing that the states of a BiRNN that correspond to zero elements of the mask consist of different states of a forward and backward network. But on the other hand, since they have zero mask elements associated with them, they should have no influence whatsoever on the output of the computation graph. Also, carrying over the state is actually good for the backward RNN, because it starts its iteration from its proper initial state (which is not zero, as you said, but a trainable vector). 

Unless Theano does not smartly optimize it away, there might be indeed some necessary computations in the gradient because of `cost * y_mask`. I do not know a better way to implement it, though.

**Comment by Beronx86** [comment]
@rizar Thanks for your reply. It solves my confusion.

I remember that Theano document talks about the gradient of the zeros in rectifier or max function. But I cannot find it.
