### ISSUE TITLE
Changing algorithm while training

### ISSUE THREAD

**Issue by Jihadik** [mila-udem/blocks#995]
Hi everybody!

I have an issue concerning changing algorithm while training. What is the best way of doing that?
For instance, simply changing `algorithm` instance in `main_loop` and then initializing it doesn't help and throws me an error.
In fact in my experiment right now I want to change only `learning_rate`, so I can make some deep surgery like `main_loop.algorithm.step_rule.blah_blah_blah.learning_rate = ...`, but I don't like this approach at all. What can you advise?

**Comment by rizar** [comment]
The solution that we had in mind is namely "deep surgery". Hyperparameters of all algorithms are usually shared Theano variables and can be changed on the go. There are two ways to fetch them: directly by accesing `algorithm.step_rule...` or by filtering the computation graph of `algorithm.updates`.

You can also create a new main loop. We did not think anticipate replacing the algorithm object, this can cause troubles.

I am closing the issue because I guess I have answered your question. By the way, the mailing list blocks-users is somewhat more appropriate when you have a question, GitHub issues are for reporting bugs.
